version: '3.9'
services:
  jenkins:
#    image: jenkins-python
    build:
      context: .
    container_name: jenkins
    restart: always
    ports:
      # - 8443:8443
      - 8080:8080
      - 50000:50000
    # environment:
    #  - JENKINS_OPTS="--httpPort=8080 --httpsPort=8443 --httpsCertificate=/var/jenkins_home/cert/jenkins.crt --httpsPrivateKey=/var/jenkins_home/cert/jenkins.key"
    volumes:
     - jenkins_home:/var/jenkins_home
     - jenkins-ssl:/var/jenkins_home/certificates
    networks:
     - jenkins-network

networks:
  jenkins-network:
    driver: bridge
volumes:
 jenkins_home:
    name: jenkins_home
 jenkins-ssl:
    name: jenkins-ssl
