services:
  jenkins_controller:
#  FIXME
#    build: .
#    image: jenkins/jenkins:2.392-jdk11
    ports:
      - "8080:8080"
      - "5000:5000"
    networks:
      - inner
      - external
    volumes:
      - jenkins_home:/var/jenkins_home
    configs:
      - httpd-config
    secrets:
      - server-certificate

#  jenkins-python-agent:
##    image: TODO
#    volumes:
#      - jenkins_agent_home:/etc/data
#    networks:
#      - inner

volumes:
  jenkins_home:
  jenkins_agent_home:
#    driver: flocker
#    driver_opts:
#      size: "10GiB"

#configs:
#  httpd-config:
#    external: true

secrets:
  server-certificate:
    external: true

networks:
  inner: {}
  external: {}

#docker run -p 8080:8080 -p 50000:50000 --restart=on-failure -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts-jdk11
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent
volumes:
  jenkins_home:


version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - JENKINS_OPTS=--httpPort=-1 --httpsPort=8443 --httpsCertificate=/var/jenkins_home/certificates/jenkins.crt --httpsPrivateKey=/var/jenkins_home/certificates/jenkins.key
    volumes:
      - jenkins-data:/var/jenkins_home
      - ./jenkins-ssl:/var/jenkins_home/certificates
volumes:
  jenkins-data:
